### ISSUE TITLE
Transition unexpected behavior v8 vs v9 (with nextjs)

### ISSUE THREAD

**Issue by stopyransky** [react-spring/react-spring#1038]
## 🐛 Bug Report

When using Transition component in v9 there is unexpected behavior of transitioned components. I've tried to follow hints from https://aleclarson.github.io/react-spring/v9/ docs but I still can't get it right.
1) it seems that a transitioned-into page is rendered twice (results in short blink) before "enter" transition
2) it seems that "leave" transition is not happening

## To Reproduce
I've prepared two sandboxes to show the issue

v8: https://codesandbox.io/s/eager-edison-60vvl  - works as expected
v9-rc3: https://codesandbox.io/s/interesting-carson-tzjkk - can't get it right

The Transition component is used in `/components/Contents.js`

## Expected behavior
Expected behavior is that every page will transition from left (enter) to right (leave).

thanks!

**Comment by stopyransky** [comment]
Hi again,

Since I am also using zustand as state management I have added a zustand store to both of above examples, and it seems that it revealed additional issue, possibly with v9 Transition, or maybe I am doing something wrong in v9 example. 

I am using store in page `One.js'. 

Once you subscribe to the store changes with `useEffect(() =>{...}, [])` you can see that the v9 is subscribing twice on mount and unsubscribes once.  The page is animated with react-spring Transition component so i assume additional re-mount is due to new Transition component. 

In similar example for v8 everything works as desired (sanboxes updated).

**Comment by aleclarson** [comment]
> 1\. it seems that a transitioned-into page is rendered twice (results in short blink) before "enter" transition

The double render is expected, because the previous page needs to be unmounted. You can wrap your pages with `React.memo` to avoid multiple renders. Or you can add `expires={false}` to your `<Transition>` element, to keep each page mounted after its first render.

&nbsp;

> 2\. it seems that "leave" transition is not happening

Your `enter` animation is missing `%` on its x-value.

```diff
  enter: {
    opacity: 1,
-   transform: "translate3d(0, 0, 0)",
+   transform: "translate3d(0%, 0, 0)",
    position: "absolute"
  },
```

&nbsp;

Also, make sure you're using the correct `page` object when rendering each transition. Your current sandbox is accidentally using the current page to render the previous page. Fix this by using the 2nd argument of the render prop.

```diff
 <Transition
   items={page}
   keys={item => item.id}
   initial={RouteChangeMotion.initial}
   from={RouteChangeMotion.from}
   enter={RouteChangeMotion.enter}
   leave={RouteChangeMotion.leave}
 >
-  {styles => {
+  {(styles, page) => {
     return (
       <animated.div style={{ ...styles, width: "100%" }}>
         <page.Component {...page.pageProps} />
       </animated.div>
     );
   }}
 </Transition>
```

Finally, you don't need to use `initial` when it's identical to `from`. In that case, it results in the same behavior whether or not you define `initial`.
