### ISSUE TITLE
Animation does not work when used with Material UI slider.

### ISSUE THREAD

**Issue by aylabyuk** [react-spring/react-spring#1068]
## 🐛 Bug Report

The `animated` function does not work when used with [MaterialUI Slider ](https://material-ui.com/components/slider/)
I was trying to set a range of values to the slider and animate based on props changes.

Seems a bug to me. haven't tried on other Material ui components tho'.

if there might be something that I missed for this to work. please enlighten me :) I added the sandbox link of this issue below.

## To Reproduce

1. wrap the component inside the `animated` function
2. define the animation using `useSpring`
3. provide the resulting value of the animation to the slider component.

## Expected behavior

animation must work

## Link to repro (highly encouraged)

[Sandbox](https://codesandbox.io/s/animating-slider-values-using-react-spring-e1gfu?file=/src/index.js)

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.13.0

**Comment by aleclarson** [comment]
The `animated` HOC uses the `ref` prop to animate the DOM node.

Since the `Slider` component gives us the DOM node for the container, and not the individual handles, we cannot animate the handles directly. Instead, you'll need to rerender the `Slider` element on every animation frame. To do that, you simply pass a function component that renders the `Slider` like this:

```js
const AnimatedSlider = animated(props => <Slider {...props}/>);
```

Since the function component does not use `React.forwardRef`, react-spring will rerender it on every animation frame instead of animating its DOM node directly.

**Comment by aylabyuk** [comment]
Thank you @aleclarson
