### ISSUE TITLE
Animated value NaN on animation with duration 0

### ISSUE THREAD

**Issue by jacobrask** [react-spring/react-spring#380]
```
    <Spring
      from={{ height: 100 }}
      to={{ height: 100 }}
      config={{ duration: 0 }}
    >
      {({ height }) => (
        <animated.div style={{ height }}>
          <div />
        </animated.div>
      )}
    </Spring>
```
https://codesandbox.io/s/jz03o39v55

In the first render, `height` will be `NaN`. I have isolated this to the following line: https://github.com/react-spring/react-spring/blob/master/src/animated/Controller.js#L319

I might be able to have a look at this myself but it won't happen before new year at least.

**Comment by drcmda** [comment]
There's a `native` missing:

    <Spring native from={...} to={...} config={...} />

If i set it all is well, as well as using a non-native spring with `div` instead of `animated.div`

**Comment by jacobrask** [comment]
My application code definitely had `native` before I reduced this issue to this sandbox.. weird

**Comment by drcmda** [comment]
I'll flag this as a bug, even if native isn't present, no reason for it to produce NaN

**Comment by jacobrask** [comment]
Seems like this was fixed by the FrameLoop changes.

**Comment by brunolemos** [comment]
I have this when changing the app theme with `immediate: true`. The first render produces `rgba(NaN, NaN, NaN, 1)`.

<img height="600" src="https://user-images.githubusercontent.com/619186/52148075-b7d56c00-264f-11e9-9e38-3ca054f39a27.png" />

**Comment by drcmda** [comment]
it's probably fixed, but could you show your code, just to make sure

**Comment by jacobrask** [comment]
My issue was definitely fixed at least

**Comment by brunolemos** [comment]
My code is a normal useSpring, the difference may be that it is in a context and being shared with dozens of components. 

Ideally I should create a small reproducible demo but if you could fork and run it would be so much easier 😄 otherwise I can try it in a few days or week

Note: The warning shows only on react-native, but probably happens on web as well and css ignores it

https://github.com/devhubapp/devhub/blob/master/packages/components/src/components/context/SpringAnimatedThemeContext.tsx

**Comment by aleclarson** [comment]
@brunolemos If you can still reproduce, please open a new issue with a minimal repository that shows it. Thanks! 👍
