### ISSUE TITLE
No auto-completion for useSpring config?

### ISSUE THREAD

**Issue by jascodes** [react-spring/react-spring#383]
I have compiled and published master with hooks types at npm @jas99/react-spring
If you see the picture below, not getting full intellisense in vscode

![screenshot from 2018-12-19 11-58-28](https://user-images.githubusercontent.com/1231593/50202858-7d588e00-0385-11e9-8e87-140ed59d39cc.png)

Thx

**Comment by jas99** [comment]
animated in react-spring/hooks missing as animated from react-spring don't seems to work for the ones for hooks
thx
![screenshot from 2018-12-19 15-34-29](https://user-images.githubusercontent.com/1231593/50213417-996b2800-03a3-11e9-8f62-614768ce3936.png)

**Comment by jas99** [comment]
cc :smile: @Kovensky

**Comment by Kovensky** [comment]
Ah, I hadn't noticed that `animated` was also exported from `hooks`.

As for intellisense "not working", it actually _is_ working, but the other way around. It is making the type of your output (the `{ opacity }` you're destructuring) be the same as the type of your inputs, and then later when you try to use it TypeScript will check if your `opacity` is compatible with the expected type of wherever you try to use it.

If you want to tell TypeScript what you want the type of your input to be instead, you can try using `useSpring<ForwardedProps<React.CSSProperties>>(...)` (`CSSProperties` because you seem to be trying to animate a `style` object).

**Comment by Kovensky** [comment]
I wonder if using it to animate `CSSProperties` is a common enough usecase. Could be worth it to add a less generic overload that matches if all the properties you give are also valid `CSSProperties`.

**Comment by jas99** [comment]
Hey @Kovensky
How do I populate SpringBaseProps, I originally was looking for for and not for css properties.

Thx

**Comment by drcmda** [comment]
@Kovensky merged the exp-chaining branch into master - it contains the latest hooks code. Btw, the offer still stands: https://github.com/react-spring/react-spring/pull/381#issuecomment-448150827 We'd be super thrilled 😊

**Comment by jas99** [comment]
Hey @drcmda 
Thx for awesome lib :smiley: 

I had couple of issues stated above, one with missing animated object from hook lib seems straight forward and the other is default props I see without using of any template; might take few tweaks by @Kovensky 

Thx

**Comment by jas99** [comment]
Hey @Kovensky #386 seems to confirm what I am saying.

**Comment by zero1995m** [comment]
Hi have great day, Problem still exist and auto-completion not work or stay in loading stage in Vscode editor.
