### ISSUE TITLE
useTransition inconsistently places elements when they are replaced

### ISSUE THREAD

**Issue by Kovensky** [react-spring/react-spring#405]
Sandbox: https://codesandbox.io/s/m7492p776p

Clicking on any button to replace it with another button (different id so different key) works differently on the first element than on the other elements. 

When you click on a button other than the first, the replacement button is positioned afterwards so the negative `marginBottom` does work to put the replacement in the correct place, making the buttons crossfade into each other.

However, when you do it on the _first_ button, the replacement appears _before_ the leaving element, so the button that is fading out gets overlaid on top of the second button, instead of on top of the first.

---

(It is possible to do this as well with `position: absolute;` but that would require `useSnapshotBeforeUpdate` to read `offsetTop` and that sounds like a bad idea and even more error-prone)

**Comment by ruggedy** [comment]
@Kovensky thanks for the christmas present. Would have a look at this

**Comment by ruggedy** [comment]
looking at the codesandbox, this is not an issue with the placement of the transition items, I believe the negative margin is screwing with the `z-index` of the items . but specifying the `z-index` seems to resolve this issue. 

Sandbox: https://codesandbox.io/s/8p2y6nmr92 

ps: you can set the `z-index` to any positive value  or my personal preference, use the item index as the `z-index`

**Comment by Kovensky** [comment]
@ruggedy the `z-index` is just hiding the animation bug (if you pay attention it still animates "on top of" the second button, it's just stacked behind); to be honest it's strange it's doing anything at all because the buttons are not `position: relative`.

**Comment by Kovensky** [comment]
@ruggedy I edited the sandbox to add a `data-state={state}` to the buttons to make it easier to see without having to look at a rapidly changing `opacity` value.

**Comment by Kovensky** [comment]
@ruggedy Made a better animation where the `z-index` change can't hide the bug: https://codesandbox.io/s/jv1k0mx35w

**Comment by ruggedy** [comment]
yh I see whats happening .. basically when trying to place elements, we try to find what element is on the element on the `left` first, then if not, we check the right. I believe whats happening here is: 

so lets assume you have an array [1 , 2, 3, 4] and you change it to [1, 2, 5, 4] i.e replacing the 3 with 5, 
at some point we will give you an array [1, 2, 3, 5,4 ] because 2 was to the left of 3. 

now if instead [1, 2, 3, 4] was changed to [5,2,3,4] we have to give you [5, 1, 2, 3, 4] as `1` does not have a left item so the speak, so we can only place it close to the item to the right. hence why the inconsistent behaviour.

relevant code block [here](https://github.com/react-spring/react-spring/blob/master/src/hooks/useTransition.js#L102) 

do you have any suggestions on how we can improve this?

**Comment by ruggedy** [comment]
@Kovensky we could remove the right check. and that would keep the items consistent. 

@drcmda  is there a reason why we check both `left` and `right`? are there any edge cases where we might lose the `left` value and so we need the `right` value to correctly place the items?

**Comment by ruggedy** [comment]
This has been resolved in 7.2.6
