### ISSUE TITLE
Initialising Keyframes.Spring state immediately on mount

### ISSUE THREAD

**Issue by alanbuchanan** [react-spring/react-spring#424]
Here I have a list whose items expand and detract using a `Keyframes.Trail` inside a `Keyframes.Spring`: https://codesandbox.io/s/1oj9155x57

The 'Ipsum' section is expanded by default:
```
  state = {
    activeName: 'Ipsum',
  };
```

The problem is that when you collapse the expanded section the first time, the animation isn't smooth. Subsequent times it's smooth and looks fine. It's just the first time which is problematic:
![expandcollapsebug](https://user-images.githubusercontent.com/10364894/50860673-758d7780-138e-11e9-82fc-cabd3de7642a.gif)

I have a feeling this is because I am animating height from `auto` to an absolute value but I am not sure why this would happen.

If I use a setTimeout to set the state in a componentDidMount, the animation is smooth and looks correct:
```
  componentDidMount() {
    setTimeout(() => {
      this.setState({ activeName: 'Ipsum' });
    }, 500);
  }
```
But of course this is not ideal.

Is there any better way of getting around this?

**Comment by drcmda** [comment]
here's where i'm at: https://codesandbox.io/s/m5jrw5wro9 getting to a similar "solution"

i have some idea what it could be. keyframes is async by nature. The first render is null because requestAnimationFrame fires later. Meanwhile the spring above tries to measure out "auto" by taking the content and rendering once in a invisible/absolute div. That div will most likely have height: 0. By using setState you are maybe changing the order a bit - all this async stuff is really complex so i'm just guessing at this point.

**Comment by alanbuchanan** [comment]
Yeah, not using `async` makes it work. Using standard objects works fine.
