### ISSUE TITLE
Is there any way to temporarily be compatible with React v15?

### ISSUE THREAD

**Issue by heartAndRain** [react-spring/react-spring#426]
My project depends on React v15 and it will take a long time to update to v16, so is there any way to temporarily be compatible with React v15?

**Comment by drcmda** [comment]
15 -> 16 wasn't a big change, just prop-types if i remember correctly (see: https://reactjs.org/blog/2017/09/26/react-v16.0.html). There's also a code-mod available, but it should be straight forward.

From our side i think it would be quite the effort because it's using all the new lifecycles, return types, context and things like forwardRefs.
