### ISSUE TITLE
useSpring not working with NextJS

### ISSUE THREAD

**Issue by sixtatami** [react-spring/react-spring#452]
when trying to import react-spring:
import { useSpring, animated } from "react-spring/hooks";

I get a:
Unhandled Rejection (SyntaxError): Unexpected token import

apparently at:
Import _inheritsLoose from '@babel/runtime/helpers/esm/inheritsLoose';

I made a minimal Next.js setup with the import here which shows the error
https://codesandbox.io/s/wy1vjy3ww7

It seems this was solved before by importing not the "esm" but the "es6" version of "inheritsLoose" but I didn't get this to work

**Comment by sixtatami** [comment]
it works with :
import { useSpring, animated } from "react-spring/hooks.cjs";

I close this

**Comment by afisher88** [comment]
I also have this problem with in Next.js with `react-spring/renderprops `

Also resolved by adding.cjs but I don't think you should need to do this.

**Comment by drcmda** [comment]
since this is coming up often, and i don't use ssr personally - how to other libs solve this? i serve esm for instance by default, because it can treeshake and is better in the browser, and cjs for require, node and old browsers. i thought most libs these days serve esm, they all would crash at thet import statement because node doesn't have imports (yet).

**Comment by ledikari** [comment]
same issue with @afisher88 , I thought I did something wrong on the setup. Thank for your solution, it really bugged me.
