### ISSUE TITLE
delay option doesn't work in useTransition

### ISSUE THREAD

**Issue by b00sta** [react-spring/react-spring#493]
I have several components with useTransition hook and want to delay transition between them using `delay`, but it doesn't work. Simple test here: https://codesandbox.io/s/2w6j5566mp

**Comment by drcmda** [comment]
delay isn't allowed for transitions, they can trail but trail starts for the second item and then accumulates for the other.

The problem is, what exactly does delay: 3000 mean. a transition goes through a myriad of state changes, for instance updates, enter, leave, initial, etc. if i allow delay, are you ok with any of these being delayed? I think it wouldn't be what you want. 

You can delay all primitives with useChain, though.

**Comment by jas99** [comment]
Hey @drcmda 
"I think it wouldn't be what you want" - Thats what hitler said :stuck_out_tongue_closed_eyes: 
Jokes aside.. 
I think more important is to allow full seprate spring configs for enter(initial too which's entering first time),leave. Let both run in parallel and when all are done transition is done. Just like Promise.all

Delay at transition level means after item(s) updates neither enter or exit happens for period of time; but can skip duration at config level since overall duration will be based on config of enter or leave.

I think its more intutive. What do you think?

**Comment by b00sta** [comment]
@drcmda. I would like the delay to be used to enter and exit the phase. I use grid for the layout components, and I also need to set `position: absolute` for each element of the grid so that the transitions look good. But the grid does not work with absolutely positioned elements. So in this case, I need to use a transition within each component and I need to trail every transition. Have you any suggestion to me?

**Comment by drcmda** [comment]
and something like this won't be better? https://codesandbox.io/embed/2v716k56pr

refs delay the entire component, but once it's started it functions normal again. to do this with a single delay prop seems not possible to me.

**Comment by jas99** [comment]
@drcmda Awesome.. and yeah this works too... and I have tried chaining couple of times always had weird duration issue, must been something by me.. this time works like charm :smiley: 

8x looking good; thx for all the time put in
Cheers :beer:

**Comment by garrettmaring** [comment]
I believe this can be accomplished with using the functional syntax.

```ts
const transitions = useTransition(show, null, {
  from: { opacity: 0 },
  enter: item => async (next, cancel) => {
    await new Promise(resolve => setTimeout(resolve, 1000));
    await next({ opacity: 1 })
  },
  leave: { opacity: 0 },
});
```

**Comment by aleclarson** [comment]
@garrettmaring In v9, you can use `delay` in the `enter`, `leave`, and `update` objects.
```ts
const transitions = useTransition(show, null, {
  from: { opacity: 0 },
  enter: { opacity: 1, delay: 1000 },
  leave: { opacity: 0 },
});
```

**Comment by garrettmaring** [comment]
Ah, very cool. Thank you @aleclarson!

**Comment by peterwiebe** [comment]
FYI just tested @aleclarson's solution with v9.0.0-rc3 and it seems that useTransition doesn't work any more. Example -> https://codesandbox.io/s/react-spring-900-rc3-usetransitions-p6u2g

**Comment by aleclarson** [comment]
@peterwiebe I've updated the comment with the latest syntax 👍

**Comment by RemyMachado** [comment]
> delay isn't allowed for transitions, the prop doesn't exist. they can trail but trail starts for the second item and then accumulates for the other.
> 
> The problem is, what exactly does delay: 3000 mean. a transition goes through a myriad of state changes, for instance updates, enter, leave, initial, etc. if i allow delay, are you ok with any of these being delayed? I think it wouldn't be what you want.
> 
> You can delay all primitives with useChain, though.

While using useChain to delay a transition I got a behavior breaking. 
I think there is a conflict between useChain and the following transition option: `order: ["leave", "enter", "update"]`

Not sure if I should fill an issue.
