### ISSUE TITLE
Why width is zero?

### ISSUE THREAD

**Issue by MrDestroii** [react-spring/react-spring#527]
https://codesandbox.io/s/vyjmyjwr1l why width is zero?

**Comment by MrDestroii** [comment]
https://codesandbox.io/s/llypkwp5nl  that's all right. But if we register in propsStyle width: open? width: 0, then width becomes zero

**Comment by drcmda** [comment]
You can only access width after rendering it out once, the first time you call the hook it doesn't know the width yet. But it doesn't matter because with resizeobserver the view auto updates, if it shrinks or grows the spring will always react to it. Updated an old treeview control yesterday that used height:auto: https://twitter.com/0xca0a/status/1094683974679621633 maybe it helps.

**Comment by MrDestroii** [comment]
> You can only access width after rendering it out once, the first time you call the hook it doesn't know the width yet. But it doesn't matter because with resizeobserver the view auto updates, if it shrinks or grows the spring will always react to it. Updated an old treeview control yesterday that used nested height:auto: https://twitter.com/0xca0a/status/1094683974679621633 maybe it helps.

why doesn’t it happen to the height?

**Comment by drcmda** [comment]
same, any attribute is zero before it is attached to the view after rendering it vie useEffect. i don't think there's a way around it, you can't know the height or width unless you have rendered it.
