### ISSUE TITLE
useTransition re-renders / mounts twice

### ISSUE THREAD

**Issue by pawelsas** [react-spring/react-spring#617]
I use `useTransition` for a transition between screens.
I've implemented this based on the Simple Transition example.

Unfortunately, the entering component renders twice which causes a flickering in my special case (scroll down using ref). I've extended the example for presentation purposes. Please see the `console.log`. https://codesandbox.io/s/y7wwzyvjkz?fontsize=14

Is there a simple way to avoid this behaviour or is it a bug?

Thanks!

**Comment by drcmda** [comment]
does look to me like its mounting twice, the line should read

```jsx
  useEffect(() => {
    console.log('Mounted')
  }, [])
```

Otherwise it's not a componentDidMount, but a componentDidUpdate in old lifecycle terms. What happens here is:

1. A mounts
2. State model changes to B
3. A is re-rendered with the old, retained state (A) which fades it out
4. B mounts and is rendered with the new state (B)

**Comment by pawelsas** [comment]
To me it looks more like it mounts on transition start (transitions.from) and on transition end (transitions.enter)?!

**Comment by drcmda** [comment]
I'm not sure i can reproduce, it mounts the A component once. Without the `[]` in the end of useEffect it will log "mounted" every time the component renders. It mounts and renders initially, and it renders once more on transition-out. When the component comes in again after clicking 3 times, it mounts again and goes through the same cycle.

**Comment by pawelsas** [comment]
Sorry, you're right.
The issue appears due to my code order. I need to include the pages [] in my Component.

I've updated the example:
https://codesandbox.io/s/y7wwzyvjkz?fontsize=14

**Comment by pawelsas** [comment]
I switched to React POSE. It works now like expected.

**Comment by elvisguillen** [comment]
@drcmda, I can confirm that @pawelsas issue is happening with me on version 8.0.19 with useTransition. I had a list with a simple accordion functionality that unintentionally re-rendered the new component after completely running the open animation. (Example with a timer in the conditionally rendered component)

![useTransition-re-render-issue](https://user-images.githubusercontent.com/4971180/56913060-b06f0480-6a7e-11e9-8d27-ccf06d88f911.gif)

Updating to React-Spring v9-beta.3 fixed this for me, not sure what the issue was exactly so I'm really looking forward to the stable release of v9. Would be helpful to know what's causing it to prevent it in the future.

![useTransition-re-render-fix](https://user-images.githubusercontent.com/4971180/56913071-b6fd7c00-6a7e-11e9-9581-1214ca11103f.gif)

Otherwise loving the new hooks, performance is a lot better with fewer renders in the profiler vs the old Props API.

Thanks!

**Comment by littlee** [comment]
should I upgrade to v9 now ?

**Comment by bailycase** [comment]
I am having the same issue of re-renders, even just calling the useTransition hook in a component causes a re-render.

**Comment by mcarabajal-technisys** [comment]
Do you have any news about this issue? Should i move to a beta version? or should i use react POSE. I will be waiting for a response, it's very importar issue in my project.

**Comment by kigorw** [comment]
Same problem. Mount - Unmount - Mount - on show, and on hide Unmount - Mount - Unmount
see https://codesandbox.io/s/react-spring-mountunmount-sbqns

**Comment by Martinnord** [comment]
This is also happening to my application when my component mounts. Would love to see a fix for this.

![mounted_twice](https://user-images.githubusercontent.com/17549362/67201366-67cd4e00-f406-11e9-81be-3987cf920cd9.gif)

**Comment by cuginoAle** [comment]
Hello,
I am having the same issue, but the bug is `Closed` !?
Is there a known workaround for this?


thanks

**Comment by tahv0** [comment]
I'm having this issue too. Any workarounds?

**Comment by aleclarson** [comment]
Anyone still seeing this bug should try v9 beta:

```sh
npm install react-spring@next
```

If that doesn't help, try the [latest v9 canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary-updated-jan-28~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 
Note: You'll need to change your `useTransition` call slightly. See #809 

If you're still having problems, please open a new issue. 👍
