### ISSUE TITLE
Ability to have multiple styles in a useTransition

### ISSUE THREAD

**Issue by edhollinghurst** [react-spring/react-spring#689]
Hi there

Really impressed with the library - thanks so much for all the effort that has obviously gone into creating it.

Just wondered whether there's any way to create multiple animation styles within a useTransition? 

E.g. in the example below, I'm looking at being able to animate page B1 from bottom to top, rather than right to left.
https://codesandbox.io/s/patient-rgb-vm1up

Any advice on this would be really appreciated.

**Comment by aleclarson** [comment]
The current API probably isn't "good enough", because you need to pass a separate function to all of the phases you wish to customize per-item ([see here](https://codesandbox.io/s/reactspringissue689-rz6yu)). It would be better to pass a single function that returns an entire set of `useTransition` props for each item, like the following:
```ts
useTransition(items, null, item => ({ ... }))
```

cc @drcmda

**Comment by edhollinghurst** [comment]
Thanks @aleclarson for the quick reply. Yes I had the same issue, it would be interesting to know if anybody has found a workaround for this.
