### ISSUE TITLE
autoFocus attribute distorts animation

### ISSUE THREAD

**Issue by saintwycliffe** [react-spring/react-spring#691]
## 🐛 Bug Report

When I add React's autoFocus feature to an `<input></input>` field, the animation for it changes.

## To Reproduce / Link to Repo

https://codesandbox.io/s/fancy-page-route-animated-xu34b

See here (on the PageOne component). To see the effect working/not-working add/remove the "autoFocus" attribute.

## Expected behavior

I want to be able to type in the field without it losing focus, yet for the animation to work on click/enter/submit.

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by shawnrice** [comment]
Some browsers force any focused element to be in view. 

So, when you focus the element, Chrome pretty much transforms the page so that the focused element is in view and then the animations are applied kind of backwards. Watch the scrollbar at the bottom to see.

You can make this work by manually calling focus on the input element itself after the transition is done. It's not so elegant, but [here's your example forked](https://codesandbox.io/s/fancy-page-route-animated-z837g).

**Comment by saintwycliffe** [comment]
@shawnrice - Thank you so much for tackling this. I'm just trying to get a handle on your code here. Do you mind explaining to me how you detect a completed animation?

**Comment by saintwycliffe** [comment]
@shawnrice - This is helpful! Thanks

**Comment by saintwycliffe** [comment]
@shawnrice - Hey, before creating another issue here, do you know why the focus on your sandbox only work *after* the first rendering? Why doesn't it work after the first animation, only subsequent animations?

**Comment by saintwycliffe** [comment]
Ah. The issue was with the phases. 

`onRest: (_, phase) => phase === "leave" && setAnimating(false)`

changed to

`onRest: _ => setAnimating(false)`

This way the state is not only effect after the "leave" phase.
