### ISSUE TITLE
Simplify internals by building useTrail atop useSprings

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring#739]
@drcmda noticed that all of the `useTrail`-specific logic could be removed since `useTrail` is really just a more constrained `useSprings`.

Take this for example:
```js
// Shorthand form (more constrained)
const props = useTrail(10, { x: 0, from: { x: 100 } })

// Identical behavior with useSprings
const props = useSprings(10, i => ({ x: 0, from: { x: 100 }, config: { mass: 1 + i } }))

// But useSprings is more flexible (because each spring has its own props)
const props = useSprings(10, i => ({ x: 0, y: i * 10, from: { x: 100, y: 0 }, config: { mass: 1 + i } }))
```

**Comment by aleclarson** [comment]
The `attach` and `parent` props actually come in handy even without `useTrail`, so we'll be keeping them. :)

**Comment by aleclarson** [comment]
Note: In #808, the `attach` and `parent` props are replaced by `to` accepting `FluidValue` types.

**Comment by drcmda** [comment]
just was talking about this with @dbismut today, so it appears like it's not exactly the same, see: https://codesandbox.io/s/react-use-gesture-template-hvscw

so this would be hard to reproduce, the closest i've gotten is: https://codesandbox.io/s/react-use-gesture-template-zvgig

but either way, i still think useSprings has lots of advantages over trail since it's more flexible and often looks more natural. i mean, unless people are really making a snake game adding up mass is probably better overall and saves us a ton of trouble with the internals.

what say you?

**Comment by dbismut** [comment]
I say we should keep it as a commodity hook at least, but it would be great to be able to select which index should be used as the "trailer" index.

**Comment by aleclarson** [comment]
**Update:** `useSprings` cannot easily achieve the same effect as `useTrail`, so we're keeping it. See its implementation [here](https://github.com/react-spring/react-spring/pull/808/files#diff-f456dc5385251b6626ae8f9f11b6fa1bR47-R64).

**Comment by simpleshadow** [comment]
Doesn't this new implementation of `useTrail` cause all the springs to occur at once, not sequentially?
