### ISSUE TITLE
How to animate variable height items in Transition

### ISSUE THREAD

**Issue by JanuaryLimes** [react-spring/react-spring#749]
Hi, is it possible to to animate variable height items in Transition? I stumbled on this strange behavior trying to do so, I tweaked a little bit demo example to illustrate what I'm trying to do:

https://codesandbox.io/embed/cocky-sutherland-c4wl6

Can you verify whether is it a bug or am I doing something wrong?

**Comment by drcmda** [comment]
yes, but measuring auto is messy and you need to employ some css safeguards like proper positioning: https://codesandbox.io/s/sad-franklin-txo47 or else there is no way to determine actual height since the fragment has to be rendered absolute for a single frame.

in the future we will remove auto completely since with hooks doing this stuff is very easy and under your full control. with hooks auto is already out.

@aleclarson this is one of the troubles i meant, we had some discussion about this recently.

**Comment by JanuaryLimes** [comment]
Thanks for the reply :wink: I will probably use solution with 'css safeguards' thing.

But I'm curious how to use useMeasure within useTransition, how can I access measured height in 'enter' transition definition? I'm sorry if it is a silly question but I have troubles understanding useTransition, can you give me an example?

**Comment by itayganor** [comment]
@JanuaryLimes Did you ever solved it?

**Comment by JanuaryLimes** [comment]
If I remember correctly I went with https://www.framer.com/api/motion/animate-presence/ from [motion](https://github.com/framer/motion)
