### ISSUE TITLE
Janky transition with images

### ISSUE THREAD

**Issue by LoicUV** [react-spring/react-spring#751]
## 🐛 Bug Report

When transitioning images with css transform rapidly (sub 1s), the animation looks broken. I forked the image fading transition example and turned it to transform3d. Use case is user is clicking on a next button of a slideshow every sub 1s

## Expected behavior

No jank 😄 

## Link to repro (highly encouraged)

https://codesandbox.io/s/dank-shape-xjsee

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x

Any idea ?

**Comment by shawnrice** [comment]
The problem is that you're using the spring timings, but your `setInterval` is setting the state on a duration. (See the note on the duration prop [in the docs](https://www.react-spring.io/docs/hooks/api)).

The simplest fix to remove the jank is to change your config from `config.molasses` to `{ ...config.molasses, duration: 700 }`; also, wrap it in a `requestAnimationFrame` in order not to drop a frame. 

See forked sandbox: https://codesandbox.io/s/dank-darkness-tshfj.

**Comment by drcmda** [comment]
https://codesandbox.io/s/elastic-kapitsa-7odjt

to me it looks more like a a css zindex issue combined with changing items too quickly. zindex is random as elements drop in and out, you can set zindex tho to fix it. the the second issue seems to be that items are dropped before they ever reach their goal.

**Comment by drcmda** [comment]
another thing is see is some general jank, but csb runs in development mode, which has the worst kind of impact on perf.

**Comment by LoicUV** [comment]
@drcmda  I initially tried to resolve a potential z fighting but to no avail, probably because the same items were being reused like you said. Anyway thanks to your input I fixed my problems which were more flickering than jank when I think about it.

Thanks !
