### ISSUE TITLE
Unexpected "Warning: Can't perform a React state update on an unmounted component"

### ISSUE THREAD

**Issue by callumbooth** [react-spring/react-spring#906]
## 🤓 Question

I have been learning react spring and I'm trying to move a div through some routes and animate the div on entry to that route, however I'm getting the warning: "Warning: Can't perform a React state update on an unmounted component" but only under specific conditions.

I have set up a code sandbox https://codesandbox.io/s/weathered-hooks-w5jl2 

When the image is clicked whilst the first animation is playing it will display the error once. However if you wait for the first animation to finish, the error never shows regardless of how many times the image is clicked.

I have created a version (change the import from 'App' to 'App2' in index.js) where it is a single component instead of passing the data down as props and the error will never appear even if the image is clicked whilst the first animation is playing.

Any ideas on how to fix this?

Full error here:
`"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ForwardRef (at Home.jsx:32)
    in Home (at App.jsx:29)`

(You _must_ search the issues before asking your question. Please consider asking in [the official Spectrum community](https://spectrum.chat/react-spring) and/or [Stack Overflow](https://stackoverflow.com) first.)

**Comment by alexvcasillas** [comment]
I'm having the same issue where whenever the component that's being animated is unmounted throws the error you've pointed. For what I've read in v9 (still in beta) this is supposed to be fixed but when I install the v9 from the @next flag it gives other errors related to hooks, so I guess it has various breaking changes that cannot find around the repo. I guess I'll have to stick with v8 and with this no-op issue until v9 is released with docs.

Anyway, give it a try to v9 and let me know if you manage to solve this because I'm interested too :)

Cheers!

**Comment by aleclarson** [comment]
This works with [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 👍

**Comment by callumbooth** [comment]
Works beautifully :) thanks
