### ISSUE TITLE
Rerendering bug

### ISSUE THREAD

**Issue by kevinkashou** [react-spring/react-spring#976]
I have a working prototype of what I am trying to achieve and I am noticing that in my console log i have index and it gets render multiple times.

https://codesandbox.io/s/small-bash-4l7ix?file=/src/index.js (My Example)

I am wondering if it has to do with useTransition causing this re-rendering.

**Comment by aleclarson** [comment]
The `useDimensions` hook is causing those unwanted rerenders. Once replaced with `100%` instead of explicit height (as seen in [this example](https://codesandbox.io/s/react-spring-976-tm7is)), your `App` component only rerenders once apart from the `index` change, which occurs because the previous `index` needs to unmount.

**Comment by kevinkashou** [comment]
@aleclarson  - But I need those set height on that container so that any content below can be seen. As you provided in your example the content is underneath the slider now. Do you have any idea how to fix that portion then?

**Comment by aleclarson** [comment]
The `react-use-dimensions` package is poorly implemented (unnecessary renders + no rAF throttling). Try using [react-use-measure](https://github.com/react-spring/react-use-measure) instead.
